dist: trusty
sudo: required

env:
  global:
  - DISPLAY=:99.0

language: java
jdk: oraclejdk8

addons:
  firefox: latest

before_script:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz
- tar -xzvf /tmp/geckodriver.tar.gz
- export PATH=$PATH:$PWD/geckodriver
- sh -e /etc/init.d/xvfb start
- sleep 5 # give xvfb some time to start

script:
  - mvn clean install

cache:
  directories:
  - $HOME/.m2
